AWSTemplateFormatVersion: '2010-09-09'
Description: Create a single EC2 instance without a key pair

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-041feb57c611358bd
      InstanceType: t2.micro          
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Hello from User Data!" > /tmp/user-data-output.txt

